In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = df = pd.read_csv(r"D:\Courses\DS&ML\Class_07-LogisticRegression&ImbalancedDataset\Customer-Churn-Prediction.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x = df.drop("Churn",axis=1)

In [8]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [9]:
y = df.Churn

In [10]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: Churn
Non-Null Count  Dtype
--------------  -----
7043 non-null   object
dtypes: object(1)
memory usage: 55.2+ KB

In [11]:
y.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: object

In [12]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.30,random_state=42)

In [13]:
xtrain.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
1695,4906-ZHGPK,Male,0,Yes,Yes,54,Yes,Yes,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Electronic check,70.70,3770
1095,7439-DKZTW,Male,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.55,80.55
3889,2592-HODOV,Male,0,No,No,13,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.30,259.65
3667,7826-VVKWT,Female,1,Yes,Yes,24,Yes,No,Fiber optic,No,No,Yes,No,Yes,Yes,Two year,Yes,Electronic check,96.55,2263.45
2902,1658-TJVOA,Female,1,No,No,6,Yes,No,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,74.10,450.9

In [14]:
ytrain.head()

1695    No
1095    No
3889    No
3667    No
2902    No
Name: Churn, dtype: object

In [15]:
print(xtrain.shape,ytrain.shape)

(4930, 20) (4930,)

## label encoding

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
ytrain_pre = le.fit_transform(ytrain)
ytest_pre = le.transform(ytest)

In [19]:
ytrain_pre

array([0, 0, 0, ..., 0, 1, 0], shape=(4930,))

In [20]:
ytest_pre

array([1, 0, 0, ..., 0, 0, 0], shape=(2113,))

In [21]:
xtrain.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [22]:
from pandas.api.types import is_numeric_dtype

In [23]:
numeric_columns = [col for col in xtrain.columns if is_numeric_dtype(xtrain[col])]

In [24]:
numeric_columns

['SeniorCitizen', 'tenure', 'MonthlyCharges']

In [25]:
categorical_columns = [col for col in xtrain.columns if not is_numeric_dtype(xtrain[col])]

In [26]:
categorical_columns

['customerID',
 'gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'TotalCharges']

In [27]:
xtrain.customerID.unique()

array(['4906-ZHGPK', '7439-DKZTW', '2592-HODOV', ..., '8044-BGWPI',
       '7450-NWRTR', '4795-UXVCJ'], shape=(4930,), dtype=object)

In [28]:
xtrain.shape

(4930, 20)

In [29]:
xtest.shape

(2113, 20)

In [31]:
xtrain = xtrain.drop(columns="customerID")
xtest = xtest.drop(columns="customerID")

In [32]:
xtrain.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
1695,Male,0,Yes,Yes,54,Yes,Yes,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Electronic check,70.70,3770
1095,Male,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.55,80.55
3889,Male,0,No,No,13,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.30,259.65
3667,Female,1,Yes,Yes,24,Yes,No,Fiber optic,No,No,Yes,No,Yes,Yes,Two year,Yes,Electronic check,96.55,2263.45
2902,Female,1,No,No,6,Yes,No,Fiber optic,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,74.10,450.9

In [34]:
xtest.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
185,Female,0,Yes,No,1,No,No phone service,DSL,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8
2715,Male,0,No,No,41,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45
3825,Female,0,Yes,Yes,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7
1807,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35
132,Male,0,No,No,67,Yes,No,DSL,No,No,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1

In [35]:
categorical_columns

['customerID',
 'gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'TotalCharges']

In [69]:
xtrain.TotalCharges.value_counts()

TotalCharges
19.75      8
           8
20.2       7
19.9       6
19.55      6
          ..
95         1
2198.3     1
306.05     1
1200.15    1
144.15     1
Name: count, Length: 4660, dtype: int64

In [70]:
xtrain.TotalCharges.unique()

array(['3770', '80.55', '259.65', ..., '306.05', '1200.15', '457.3'],
      shape=(4660,), dtype=object)

In [72]:
xtrain['TotalCharges'] = pd.to_numeric(xtrain.TotalCharges,errors='coerce')
xtest['TotalCharges'] = pd.to_numeric(xtest.TotalCharges,errors='coerce')

In [73]:
xtrain.TotalCharges.isnull().sum()

np.int64(8)

In [74]:
xtrain.TotalCharges.fillna(xtrain.TotalCharges.median(),inplace=True)
xtest.TotalCharges.fillna(xtest.TotalCharges.median(),inplace=True)

In [75]:
ordinal_en_columns = ['gender','Partner','Dependents','PhoneService','Contract','PaperlessBilling']

In [76]:
one_hoten_columns = ['MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection',
                     'TechSupport','StreamingTV','StreamingMovies','PaymentMethod']

In [77]:
xtrain.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4930 entries, 1695 to 860
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            4930 non-null   object
 1   SeniorCitizen     4930 non-null   int64
 2   Partner           4930 non-null   object
 3   Dependents        4930 non-null   object
 4   tenure            4930 non-null   int64
 5   PhoneService      4930 non-null   object
 6   MultipleLines     4930 non-null   object
 7   InternetService   4930 non-null   object
 8   OnlineSecurity    4930 non-null   object
 9   OnlineBackup      4930 non-null   object
 10  DeviceProtection  4930 non-null   object
 11  TechSupport       4930 non-null   object
 12  StreamingTV       4930 non-null   object
 13  StreamingMovies   4930 non-null   object
 14  Contract          4930 non-null   object
 15  PaperlessBilling  4930 non-null   object
 16  PaymentMethod     4930 non-null   object
 17  MonthlyCharges    4930 non-null   float64
 18  TotalCharges      4930 non-null   float64
dtypes: float64(2), int64(2), object(15)
memory usage: 899.4+ KB

In [78]:
df.Churn.value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [79]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [81]:
from sklearn.compose import ColumnTransformer
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

In [82]:
preprocessor = ColumnTransformer(
    transformers=[
        ('ont_hot',OneHotEncoder(handle_unknown='ignore'),one_hoten_columns),
        ('ordinal',OrdinalEncoder(),ordinal_en_columns)
    ]
)

In [83]:
models = {
    "LogisticRegression": LogisticRegression(),
    "DecisionTreeClassifier": DecisionTreeClassifier(),
    "KNeighborsClassifier": KNeighborsClassifier()
}

In [85]:
for name,model in models.items():
    # print(name,model)
    clf = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("smote",SMOTE()),
        ("model",model)
    ])
    clf.fit(xtrain,ytrain)
    clf.predict(xtest)
    print(f"Training score is, {name}: {clf.score(xtrain,ytrain)}")
    print(f"test score is, {name}: {clf.score(xtest,ytest)}")

Training score is, LogisticRegression: 0.7304259634888438
test score is, LogisticRegression: 0.738760056791292
Training score is, DecisionTreeClassifier: 0.9127789046653144
test score is, DecisionTreeClassifier: 0.7307146237576905
Training score is, KNeighborsClassifier: 0.8008113590263691
test score is, KNeighborsClassifier: 0.6914339801230478